version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./static:/var/www/CityGid/YourGid/src/main/resources/
      - ./images:/var/www/CityGid/YourGid/src/main/resources/static/
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email puzzle.volga@gmail.com --agree-tos --no-eff-email --force-renewal -d thisispuzzle.ru -d www.thisispuzzle.ru

  postgres:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: CityGid
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: yourgid_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/var/www/CityGid/YourGid/src/main/resources/
      - ./images:/var/www/CityGid/YourGid/src/main/resources/static/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/CityGid
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  static:
  images:
  postgres-data:

networks:
  app-network:
    driver: bridge